kind: BuildConfig
apiVersion: v1
metadata:
  name: gitlab-github-bridge
spec:
  runPolicy: Serial
  source: 
    dockerfile: |
      FROM docker.io/joschi64/gitlab-github-bridge:latest
  strategy: 
    dockerStrategy:
    type: Docker
  output: 
    to:
      kind: ImageStreamTag
      name: is-gitlab-github-bridge:latest
